all: pid fork1 fork2 infloop fork

pid: pid.c
	gcc pid.c -o pid -Wall -g

fork1: fork1.c
	gcc fork1.c -o fork1 -Wall -g

fork2: fork2.c
	gcc fork2.c -o fork2 -Wall -g

infloop: infloop.c
	gcc infloop.c -o infloop -Wall -g

fork: fork.c
	gcc fork.c -o fork -Wall -g
